/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/corePageAnis-v1': RouteRecordInfo<'/corePageAnis-v1', '/corePageAnis-v1', Record<never, never>, Record<never, never>>,
    '/corePageAnis-v2': RouteRecordInfo<'/corePageAnis-v2', '/corePageAnis-v2', Record<never, never>, Record<never, never>>,
    '/corePageKevin-v1': RouteRecordInfo<'/corePageKevin-v1', '/corePageKevin-v1', Record<never, never>, Record<never, never>>,
    '/corePageKevin-v2': RouteRecordInfo<'/corePageKevin-v2', '/corePageKevin-v2', Record<never, never>, Record<never, never>>,
    '/corePageKevin-v3': RouteRecordInfo<'/corePageKevin-v3', '/corePageKevin-v3', Record<never, never>, Record<never, never>>,
  }
}
